apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/joshuamkite/eks-argocd.git
        revision: feature/crossplane
        files:
          - path: "argocd/applications/**.yaml"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://aws.github.io/eks-charts
        targetRevision: 1.7.2
        chart: aws-load-balancer-controller
        helm:
          values: |
            clusterName: personal-eks-workshop
            serviceAccount:
              create: true
              annotations:
                eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/AWSLoadBalancerControllerRole"
              name: aws-load-balancer-controller
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
