apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/joshuamkite/eks-argocd.git
        revision: feature/argocd
        directories:
          - path: argocd/applications/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/joshuamkite/eks-argocd.git
        targetRevision: feature/argocd
        path: "argocd/applications/{{path.basename}}"
        helm:
          valueFiles:
            - "configs/{{path.basename}}/values.yaml"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
